-- HIGHLUX MNL — complete database setup for a NEW Supabase project.
-- Paste this whole file into Supabase → SQL Editor → New query → Run (once).
-- Generated by scripts/build-setup-sql.mjs from 5 migrations + seed. Do not edit by hand.
-- For later schema changes, run only the new migration files.

-- ═══ 20261008000001_catalog.sql ═══
-- HIGHLUX MNL — Phase 1: catalog, site content, profiles & roles.
-- Orders/payments/layaway (Phase 3) and consignments (Phase 5) ship as later migrations.

create extension if not exists "pgcrypto";

-- ─── Enums ───────────────────────────────────────────────────────────────
create type public.product_category as enum ('bags', 'watches', 'jewelry', 'accessories');
create type public.condition_grade  as enum ('brand_new', 'pristine', 'excellent', 'very_good', 'good');
create type public.product_status   as enum ('available', 'reserved', 'sold', 'hidden');
create type public.user_role        as enum ('customer', 'staff', 'admin');

-- ─── Profiles (1:1 with auth.users) ──────────────────────────────────────
create table public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text,
  phone       text,
  role        public.user_role not null default 'customer',
  created_at  timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'));
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Role lookups go through security-definer functions so profile policies don't recurse.
create or replace function public.current_user_role()
returns public.user_role language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('staff', 'admin'));
$$;

-- ─── Brands ──────────────────────────────────────────────────────────────
create table public.brands (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  slug        text not null unique,
  categories  public.product_category[] not null default '{}',
  logo_url    text,
  sort_order  int not null default 0
);

-- ─── Products ────────────────────────────────────────────────────────────
create table public.products (
  id                          uuid primary key default gen_random_uuid(),
  slug                        text not null unique,
  brand_id                    uuid not null references public.brands (id),
  model                       text not null,
  title                       text not null,
  category                    public.product_category not null,
  sub_category                text not null,
  price                       numeric(12, 2) not null check (price >= 0),
  compare_at_price            numeric(12, 2) check (compare_at_price is null or compare_at_price >= 0),
  condition                   public.condition_grade not null,
  condition_notes             text,
  inclusions                  text[] not null default '{}',
  authenticity_method         text,
  authenticity_certificate_url text,
  specs                       jsonb not null default '{}'::jsonb,
  color                       text,
  video_url                   text,
  status                      public.product_status not null default 'available',
  -- Single-unit stock: an item in checkout is held until reserved_until.
  reserved_until              timestamptz,
  reserved_by                 uuid references auth.users (id) on delete set null,
  featured                    boolean not null default false,
  description                 text,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  sold_at                     timestamptz
);

create index products_category_idx on public.products (category, status);
create index products_brand_idx    on public.products (brand_id);
create index products_created_idx  on public.products (created_at desc);
create index products_search_idx   on public.products
  using gin (to_tsvector('simple', title || ' ' || model || ' ' || coalesce(color, '')));

create table public.product_images (
  id          uuid primary key default gen_random_uuid(),
  product_id  uuid not null references public.products (id) on delete cascade,
  url         text not null,
  alt         text not null default '',
  position    int  not null default 0
);
create index product_images_product_idx on public.product_images (product_id, position);

-- Max 15 photos per product.
create or replace function public.enforce_image_limit()
returns trigger language plpgsql as $$
begin
  if (select count(*) from public.product_images where product_id = new.product_id) >= 15 then
    raise exception 'A product can have at most 15 photos';
  end if;
  return new;
end $$;
create trigger product_images_limit before insert on public.product_images
  for each row execute function public.enforce_image_limit();

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
create trigger products_touch before update on public.products
  for each row execute function public.touch_updated_at();

-- ─── Site content (homepage editor, shipping rates, etc.) ────────────────
create table public.site_settings (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now()
);

create table public.reviews (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  location    text,
  rating      int not null check (rating between 1 and 5),
  body        text not null,
  item        text,
  published   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table public.newsletter_subscribers (
  id          uuid primary key default gen_random_uuid(),
  email       text not null unique,
  created_at  timestamptz not null default now()
);

-- ─── Row Level Security ──────────────────────────────────────────────────
alter table public.profiles               enable row level security;
alter table public.brands                 enable row level security;
alter table public.products               enable row level security;
alter table public.product_images         enable row level security;
alter table public.site_settings          enable row level security;
alter table public.reviews                enable row level security;
alter table public.newsletter_subscribers enable row level security;

create policy "own profile read"   on public.profiles for select using (id = auth.uid() or public.is_staff());
create policy "own profile update" on public.profiles for update using (id = auth.uid())
  with check (id = auth.uid() and role = public.current_user_role());  -- customers can't self-promote
create policy "staff manage profiles" on public.profiles for all using (public.is_staff()) with check (public.is_staff());

create policy "public read brands" on public.brands for select using (true);
create policy "staff write brands" on public.brands for all using (public.is_staff()) with check (public.is_staff());

-- Sold items stay visible as social proof; only 'hidden' is private.
create policy "public read products" on public.products for select using (status <> 'hidden' or public.is_staff());
create policy "staff write products" on public.products for all using (public.is_staff()) with check (public.is_staff());

create policy "public read images" on public.product_images for select using (
  exists (select 1 from public.products p where p.id = product_id and (p.status <> 'hidden' or public.is_staff()))
);
create policy "staff write images" on public.product_images for all using (public.is_staff()) with check (public.is_staff());

create policy "public read settings" on public.site_settings for select using (true);
create policy "staff write settings" on public.site_settings for all using (public.is_staff()) with check (public.is_staff());

create policy "public read reviews" on public.reviews for select using (published or public.is_staff());
create policy "staff write reviews" on public.reviews for all using (public.is_staff()) with check (public.is_staff());

create policy "anyone subscribes" on public.newsletter_subscribers for insert with check (true);
create policy "staff read subscribers" on public.newsletter_subscribers for select using (public.is_staff());

-- ─── Storage ─────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public) values
  ('product-media', 'product-media', true),
  ('site-assets',   'site-assets',   true)
on conflict (id) do nothing;

create policy "public read product media" on storage.objects for select
  using (bucket_id in ('product-media', 'site-assets'));
create policy "staff upload media" on storage.objects for insert
  with check (bucket_id in ('product-media', 'site-assets') and public.is_staff());
create policy "staff update media" on storage.objects for update
  using (bucket_id in ('product-media', 'site-assets') and public.is_staff());
create policy "staff delete media" on storage.objects for delete
  using (bucket_id in ('product-media', 'site-assets') and public.is_staff());

-- ═══ 20261008000002_orders.sql ═══
-- HIGHLUX MNL — Phase 3: orders, payments, layaway, item holds.
--
-- Hold model (each piece is one of a kind):
--   * Entering checkout holds items for the customer's browser session for 15 min
--     (products.status = 'reserved', reserved_session = <session id>, reserved_until = now()+15m).
--   * Placing an order transfers the hold to the order (reserved_session = 'order:<id>')
--     and extends it while the customer pays (PayMongo / bank transfer / meet-up).
--   * A layaway down payment holds the item indefinitely (reserved_until = null).
--   * Full payment marks it sold.
--   * Holds past reserved_until are treated as available and swept by expire_holds().
-- All writes go through the service role (server only); customers only read their own orders.

alter table public.products add column reserved_session text;
create index products_reserved_idx on public.products (reserved_until) where status = 'reserved';

create type public.order_status       as enum ('pending_payment', 'layaway', 'paid', 'packed', 'shipped', 'delivered', 'cancelled', 'expired');
create type public.fulfillment_method as enum ('ship_metro_manila', 'ship_provincial', 'meetup', 'pickup');
create type public.payment_method     as enum ('gcash', 'maya', 'card', 'bank_transfer', 'pay_at_meetup');
create type public.payment_status     as enum ('pending', 'paid', 'failed', 'rejected', 'expired');

create sequence public.order_number_seq start 1001;

create table public.orders (
  id                uuid primary key default gen_random_uuid(),
  order_number      text not null unique default ('HLX-' || nextval('public.order_number_seq')),
  -- Secret for guest order tracking links (/orders/HLX-1001?t=...).
  access_token      text not null default encode(gen_random_bytes(18), 'hex'),
  user_id           uuid references auth.users (id) on delete set null,
  email             text not null,
  full_name         text not null,
  phone             text not null,
  fulfillment       public.fulfillment_method not null,
  shipping_address  jsonb,
  notes             text,
  payment_method    public.payment_method not null,
  payment_plan      text not null default 'full' check (payment_plan in ('full', 'layaway')),
  subtotal          numeric(12, 2) not null,
  shipping_fee      numeric(12, 2) not null default 0,
  total             numeric(12, 2) not null,
  amount_paid       numeric(12, 2) not null default 0,
  status            public.order_status not null default 'pending_payment',
  hold_expires_at   timestamptz,
  -- Set when a payment lands for an item that is no longer held for this order (e.g. paid after expiry).
  needs_review      boolean not null default false,
  review_note       text,
  courier           text,
  tracking_number   text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  paid_at           timestamptz,
  packed_at         timestamptz,
  shipped_at        timestamptz,
  delivered_at      timestamptz
);
create index orders_user_idx    on public.orders (user_id, created_at desc);
create index orders_status_idx  on public.orders (status, created_at desc);
create index orders_email_idx   on public.orders (lower(email));
create trigger orders_touch before update on public.orders for each row execute function public.touch_updated_at();

create table public.order_items (
  id          uuid primary key default gen_random_uuid(),
  order_id    uuid not null references public.orders (id) on delete cascade,
  product_id  uuid not null references public.products (id),
  title       text not null,
  brand       text not null,
  price       numeric(12, 2) not null,
  image_url   text
);
create index order_items_order_idx on public.order_items (order_id);

create table public.layaway_installments (
  id          uuid primary key default gen_random_uuid(),
  order_id    uuid not null references public.orders (id) on delete cascade,
  seq         int  not null,          -- 0 = down payment
  due_date    date not null,
  amount      numeric(12, 2) not null,
  status      text not null default 'due' check (status in ('due', 'paid')),
  paid_at     timestamptz,
  unique (order_id, seq)
);

create table public.payments (
  id                uuid primary key default gen_random_uuid(),
  order_id          uuid not null references public.orders (id) on delete cascade,
  amount            numeric(12, 2) not null check (amount > 0),
  method            public.payment_method not null,
  status            public.payment_status not null default 'pending',
  provider          text,               -- 'paymongo' | 'manual'
  provider_ref      text unique,        -- PayMongo checkout session id
  checkout_url      text,
  proof_path        text,               -- storage path in payment-proofs bucket
  reference_no      text,               -- bank reference entered by the customer
  reviewed_by       uuid references auth.users (id),
  reviewed_at       timestamptz,
  rejection_reason  text,
  created_at        timestamptz not null default now(),
  paid_at           timestamptz
);
create index payments_order_idx on public.payments (order_id, created_at);
create index payments_review_idx on public.payments (status) where proof_path is not null;

-- ─── RLS: customers read their own orders; staff read everything; writes = service role ───
alter table public.orders               enable row level security;
alter table public.order_items          enable row level security;
alter table public.layaway_installments enable row level security;
alter table public.payments             enable row level security;

create policy "own orders"      on public.orders for select using (user_id = auth.uid() or public.is_staff());
create policy "staff orders"    on public.orders for update using (public.is_staff()) with check (public.is_staff());
create policy "own items"       on public.order_items for select using (
  exists (select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_staff())));
create policy "own installments" on public.layaway_installments for select using (
  exists (select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_staff())));
create policy "own payments"    on public.payments for select using (
  exists (select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_staff())));

-- Private bucket for proof-of-payment uploads (written by the server, read via signed URLs).
insert into storage.buckets (id, name, public) values ('payment-proofs', 'payment-proofs', false)
on conflict (id) do nothing;
create policy "staff read proofs" on storage.objects for select using (bucket_id = 'payment-proofs' and public.is_staff());

-- ─── Holds ───────────────────────────────────────────────────────────────

/** Is this product free for `p_holder` to take? (available, already theirs, or an expired timed hold) */
create or replace function public.product_takeable(p public.products, p_holder text)
returns boolean language sql stable as $$
  select p.status = 'available'
      or (p.status = 'reserved' and (
            p.reserved_session = p_holder
         or (p.reserved_until is not null and p.reserved_until < now())));
$$;

/** Hold items for a checkout session. Takes what it can; returns one row per requested id. */
create or replace function public.reserve_products(p_ids uuid[], p_session text, p_minutes int)
returns table (product_id uuid, held boolean, reserved_until timestamptz)
language plpgsql security definer set search_path = public as $$
begin
  -- UPDATE row-locks and re-checks its WHERE after any concurrent writer commits,
  -- so two shoppers can't both take the same piece. Live order holds aren't takeable.
  return query
  with taken as (
    update products p
       set status = 'reserved', reserved_session = p_session, reserved_until = now() + make_interval(mins => p_minutes)
     where p.id = any(p_ids) and public.product_takeable(p, p_session)
    returning p.id, p.reserved_until
  )
  select i.id, t.id is not null, t.reserved_until
    from unnest(p_ids) as i(id)
    left join taken t on t.id = i.id;
end $$;

/** Release a session's holds (customer removed an item from the bag). */
create or replace function public.release_products(p_ids uuid[], p_session text)
returns void language sql security definer set search_path = public as $$
  update products set status = 'available', reserved_session = null, reserved_until = null
   where id = any(p_ids) and status = 'reserved' and reserved_session = p_session;
$$;

/**
 * Atomically create an order from held items. Prices are re-read under lock and
 * must match p_expected_subtotal (the server computed shipping/layaway from it).
 * Raises ITEM_UNAVAILABLE:<ids> or PRICE_CHANGED.
 */
create or replace function public.place_order(
  p_session text, p_product_ids uuid[], p_expected_subtotal numeric, p_hold_minutes int,
  p_order jsonb, p_installments jsonb
) returns public.orders
language plpgsql security definer set search_path = public as $$
declare
  v_order   orders;
  v_bad     uuid[];
  v_sub     numeric;
begin
  if coalesce(array_length(p_product_ids, 1), 0) = 0 then raise exception 'EMPTY_ORDER'; end if;

  perform 1 from products where id = any(p_product_ids) for update;

  select array_agg(i.id) into v_bad
    from unnest(p_product_ids) i(id)
    left join products p on p.id = i.id
   where p.id is null or not public.product_takeable(p, p_session);
  if v_bad is not null then raise exception 'ITEM_UNAVAILABLE:%', array_to_string(v_bad, ','); end if;

  select sum(price) into v_sub from products where id = any(p_product_ids);
  if v_sub <> p_expected_subtotal then raise exception 'PRICE_CHANGED'; end if;

  insert into orders (user_id, email, full_name, phone, fulfillment, shipping_address, notes,
                      payment_method, payment_plan, subtotal, shipping_fee, total, hold_expires_at)
  values (nullif(p_order ->> 'user_id', '')::uuid, p_order ->> 'email', p_order ->> 'full_name', p_order ->> 'phone',
          (p_order ->> 'fulfillment')::fulfillment_method, p_order -> 'shipping_address', p_order ->> 'notes',
          (p_order ->> 'payment_method')::payment_method, p_order ->> 'payment_plan',
          v_sub, (p_order ->> 'shipping_fee')::numeric, v_sub + (p_order ->> 'shipping_fee')::numeric,
          now() + make_interval(mins => p_hold_minutes))
  returning * into v_order;

  insert into order_items (order_id, product_id, title, brand, price, image_url)
  select v_order.id, p.id, p.title, b.name, p.price,
         (select url from product_images i where i.product_id = p.id order by position limit 1)
    from products p join brands b on b.id = p.brand_id
   where p.id = any(p_product_ids);

  insert into layaway_installments (order_id, seq, due_date, amount)
  select v_order.id, (x ->> 'seq')::int, (x ->> 'due_date')::date, (x ->> 'amount')::numeric
    from jsonb_array_elements(coalesce(p_installments, '[]'::jsonb)) x;

  update products set status = 'reserved', reserved_session = 'order:' || v_order.id, reserved_until = v_order.hold_expires_at
   where id = any(p_product_ids);

  return v_order;
end $$;

/**
 * Mark a payment paid and apply it to its order. Idempotent (re-delivered
 * webhooks are no-ops). Fully paid → items sold; partially paid layaway →
 * items held indefinitely for the customer.
 */
create or replace function public.record_payment(p_payment_id uuid)
returns public.orders
language plpgsql security definer set search_path = public as $$
declare
  v_pay    payments;
  v_order  orders;
  v_ids    uuid[];
  v_claim  int;
  v_left   numeric;
  r        record;
begin
  select * into v_pay from payments where id = p_payment_id for update;
  if not found then raise exception 'PAYMENT_NOT_FOUND'; end if;
  select * into v_order from orders where id = v_pay.order_id for update;
  if v_pay.status = 'paid' then return v_order; end if;

  update payments set status = 'paid', paid_at = now() where id = v_pay.id;
  v_order.amount_paid := v_order.amount_paid + v_pay.amount;

  -- Allocate cumulative payments to installments in order.
  v_left := v_order.amount_paid;
  for r in select * from layaway_installments where order_id = v_order.id order by seq loop
    exit when v_left < r.amount;
    v_left := v_left - r.amount;
    if r.status = 'due' then
      update layaway_installments set status = 'paid', paid_at = now() where id = r.id;
    end if;
  end loop;

  select array_agg(product_id) into v_ids from order_items where order_id = v_order.id;

  -- (Re)claim the items for this order; fails only if someone else took them after this order's hold lapsed.
  with claim as (
    update products p set status = 'reserved', reserved_session = 'order:' || v_order.id, reserved_until = null
     where p.id = any(v_ids)
       and (public.product_takeable(p, 'order:' || v_order.id))
    returning 1
  ) select count(*) into v_claim from claim;
  if v_claim < coalesce(array_length(v_ids, 1), 0) then
    v_order.needs_review := true;
    v_order.review_note := concat_ws(E'\n', v_order.review_note,
      format('%s: payment of %s received but an item was no longer held for this order — refund or substitute.', now()::date, v_pay.amount));
  end if;

  if v_order.amount_paid >= v_order.total then
    update products set status = 'sold', sold_at = now(), reserved_session = null, reserved_until = null
     where id = any(v_ids) and reserved_session = 'order:' || v_order.id;
    v_order.status := case when v_order.status in ('pending_payment', 'layaway', 'expired', 'cancelled') then 'paid' else v_order.status end;
    v_order.paid_at := coalesce(v_order.paid_at, now());
  elsif v_order.payment_plan = 'layaway' then
    v_order.status := case when v_order.status in ('pending_payment', 'expired', 'cancelled') then 'layaway' else v_order.status end;
  end if;
  v_order.hold_expires_at := null;

  update orders set amount_paid = v_order.amount_paid, status = v_order.status, paid_at = v_order.paid_at,
                    hold_expires_at = null, needs_review = v_order.needs_review, review_note = v_order.review_note
   where id = v_order.id
  returning * into v_order;
  return v_order;
end $$;

/** A bank-transfer proof is awaiting review: stop the clock so the hold doesn't lapse meanwhile. */
create or replace function public.pause_hold_for_review(p_order_id uuid)
returns void language sql security definer set search_path = public as $$
  update orders set hold_expires_at = null where id = p_order_id and status = 'pending_payment';
  update products set reserved_until = null
   where reserved_session = 'order:' || p_order_id and status = 'reserved';
$$;

/** Sweep: expire unpaid orders whose hold lapsed and release every lapsed hold. Run by cron. */
create or replace function public.expire_holds()
returns int language plpgsql security definer set search_path = public as $$
declare n int;
begin
  update orders set status = 'expired'
   where status = 'pending_payment' and hold_expires_at is not null and hold_expires_at < now();
  update payments set status = 'expired'
   where status = 'pending' and proof_path is null
     and order_id in (select id from orders where status = 'expired');
  update products set status = 'available', reserved_session = null, reserved_until = null
   where status = 'reserved' and reserved_until is not null and reserved_until < now();
  get diagnostics n = row_count;
  return n;
end $$;

revoke execute on function public.reserve_products, public.release_products, public.place_order,
  public.record_payment, public.pause_hold_for_review, public.expire_holds from public, anon, authenticated;

-- Default checkout settings (editable in the admin in Phase 5).
insert into public.site_settings (key, value) values ('checkout', '{}'::jsonb) on conflict (key) do nothing;

-- ═══ 20261009000003_accounts.sql ═══
-- HIGHLUX MNL — Phase 4: customer accounts (saved addresses, synced wishlist).
-- Auth itself is Supabase Auth (email + Google). profiles rows are created by
-- the on_auth_user_created trigger from Phase 1.

create table public.customer_addresses (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,
  label       text not null default 'Home',
  full_name   text not null,
  phone       text not null,
  line1       text not null,
  barangay    text not null,
  city        text not null,
  province    text not null,
  zip         text not null check (zip ~ '^\d{4}$'),
  is_default  boolean not null default false,
  created_at  timestamptz not null default now()
);
create index customer_addresses_user_idx on public.customer_addresses (user_id, created_at);
-- At most one default address per customer.
create unique index customer_addresses_one_default on public.customer_addresses (user_id) where is_default;

create table public.wishlist_items (
  user_id     uuid not null references auth.users (id) on delete cascade,
  product_id  uuid not null references public.products (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, product_id)
);

alter table public.customer_addresses enable row level security;
alter table public.wishlist_items     enable row level security;

create policy "own addresses" on public.customer_addresses for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "staff read addresses" on public.customer_addresses for select using (public.is_staff());

create policy "own wishlist" on public.wishlist_items for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

grant select, insert, update, delete on public.customer_addresses, public.wishlist_items to authenticated;
grant update (full_name, phone) on public.profiles to authenticated;

/** Make one address the default (clears the previous default atomically). */
create or replace function public.set_default_address(p_address_id uuid)
returns void language plpgsql security invoker set search_path = public as $$
begin
  update customer_addresses set is_default = false where user_id = auth.uid() and is_default and id <> p_address_id;
  update customer_addresses set is_default = true  where user_id = auth.uid() and id = p_address_id;
end $$;
grant execute on function public.set_default_address to authenticated;

-- ═══ 20261009000004_admin.sql ═══
-- HIGHLUX MNL — Phase 5: admin operations + consignment submissions.

-- ─── Consignments ("Sell to Us") ─────────────────────────────────────────
create type public.consignment_status as enum ('new', 'reviewing', 'offered', 'accepted', 'declined', 'received');

create table public.consignments (
  id            uuid primary key default gen_random_uuid(),
  full_name     text not null,
  email         text not null,
  phone         text not null,
  city          text,
  brand         text not null,
  category      text not null,
  model         text not null,
  condition     text,
  inclusions    text[] not null default '{}',
  purchase_year text,
  asking_price  numeric(12, 2),
  wants         text not null default 'sell' check (wants in ('sell', 'consign', 'either')),
  notes         text,
  photo_paths   text[] not null default '{}',   -- private bucket "consignments"
  status        public.consignment_status not null default 'new',
  admin_notes   text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index consignments_status_idx on public.consignments (status, created_at desc);
create trigger consignments_touch before update on public.consignments for each row execute function public.touch_updated_at();

-- Submitted through the server (service role); only staff can read or manage.
alter table public.consignments enable row level security;
create policy "staff manage consignments" on public.consignments for all using (public.is_staff()) with check (public.is_staff());

insert into storage.buckets (id, name, public) values ('consignments', 'consignments', false) on conflict (id) do nothing;
create policy "staff read consignment photos" on storage.objects for select using (bucket_id = 'consignments' and public.is_staff());

-- Internal notes on orders (staff only; never shown to customers).
alter table public.orders add column admin_notes text;
alter table public.orders add column cancelled_at timestamptz;

-- ─── Order operations ────────────────────────────────────────────────────

/** Staff rejected a bank-transfer proof: mark it, and give the customer time to upload a correct one. */
create or replace function public.reject_payment(p_payment_id uuid, p_reviewer uuid, p_reason text, p_hold_hours int)
returns public.orders language plpgsql security definer set search_path = public as $$
declare v_pay payments; v_order orders;
begin
  select * into v_pay from payments where id = p_payment_id for update;
  if not found then raise exception 'PAYMENT_NOT_FOUND'; end if;
  if v_pay.status <> 'pending' then raise exception 'PAYMENT_NOT_PENDING'; end if;
  update payments set status = 'rejected', rejection_reason = p_reason, reviewed_by = p_reviewer, reviewed_at = now() where id = v_pay.id;
  select * into v_order from orders where id = v_pay.order_id for update;
  if v_order.status = 'pending_payment' then
    -- Restart the clock so the piece isn't held forever on a bad proof.
    update orders set hold_expires_at = now() + make_interval(hours => p_hold_hours) where id = v_order.id returning * into v_order;
    update products set reserved_until = v_order.hold_expires_at
     where reserved_session = 'order:' || v_order.id and status = 'reserved';
  end if;
  return v_order;
end $$;

/** Cancel an unpaid (or layaway) order and release its pieces. Fully paid orders can't be cancelled here (refund first). */
create or replace function public.cancel_order(p_order_id uuid)
returns public.orders language plpgsql security definer set search_path = public as $$
declare v_order orders;
begin
  select * into v_order from orders where id = p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if v_order.status not in ('pending_payment', 'layaway', 'expired') then raise exception 'ORDER_NOT_CANCELLABLE'; end if;
  update products set status = 'available', reserved_session = null, reserved_until = null
   where reserved_session = 'order:' || v_order.id and status = 'reserved';
  update payments set status = 'expired' where order_id = v_order.id and status = 'pending';
  update orders set status = 'cancelled', cancelled_at = now(), hold_expires_at = null where id = v_order.id returning * into v_order;
  return v_order;
end $$;

revoke execute on function public.reject_payment, public.cancel_order from public, anon, authenticated;

-- ═══ 20261009000005_marketing.sql ═══
-- HIGHLUX MNL — Phase 6: ad attribution captured at checkout (Meta Pixel cookies,
-- IP and user agent) so the server-side Purchase event can be matched to the ad click.
alter table public.orders add column attribution jsonb;
comment on column public.orders.attribution is 'Meta CAPI matching data captured at checkout: {fbp, fbc, ip, ua}. Staff/service only.';

-- ═══ seed.sql (12 sample products, reviews, homepage) ═══
-- Generated by scripts/generate-seed.ts — do not edit by hand.
begin;
insert into public.brands (name, slug, categories, sort_order) values ('Hermès', 'hermes', array['bags', 'jewelry', 'accessories']::public.product_category[], 0) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Chanel', 'chanel', array['bags', 'jewelry', 'accessories']::public.product_category[], 1) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Louis Vuitton', 'louis-vuitton', array['bags', 'accessories']::public.product_category[], 2) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Dior', 'dior', array['bags', 'accessories']::public.product_category[], 3) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Gucci', 'gucci', array['bags', 'accessories']::public.product_category[], 4) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Prada', 'prada', array['bags', 'accessories']::public.product_category[], 5) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Goyard', 'goyard', array['bags', 'accessories']::public.product_category[], 6) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Bottega Veneta', 'bottega-veneta', array['bags']::public.product_category[], 7) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Rolex', 'rolex', array['watches']::public.product_category[], 8) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Audemars Piguet', 'audemars-piguet', array['watches']::public.product_category[], 9) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Patek Philippe', 'patek-philippe', array['watches']::public.product_category[], 10) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Omega', 'omega', array['watches']::public.product_category[], 11) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Cartier', 'cartier', array['watches', 'jewelry']::public.product_category[], 12) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Tiffany & Co.', 'tiffany-and-co', array['jewelry']::public.product_category[], 13) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Van Cleef & Arpels', 'van-cleef-and-arpels', array['jewelry']::public.product_category[], 14) on conflict (slug) do nothing;
insert into public.brands (name, slug, categories, sort_order) values ('Bulgari', 'bulgari', array['jewelry', 'watches']::public.product_category[], 15) on conflict (slug) do nothing;
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000001', 'louis-vuitton-speedy-30-monogram', (select id from public.brands where slug = 'louis-vuitton'), 'Speedy 30', 'Louis Vuitton Speedy 30 Monogram', 'bags', 'top-handle-bags', 48000, 55000, 'excellent', 'Light patina on vachetta handles. Clean interior. Minor scuffs on base corners.', array['dust_bag', 'lock_and_key']::text[], 'Entrupy verified', '{"measurements":"30 × 21 × 17 cm","material":"Monogram coated canvas","color":"Brown","hardware":"Gold-tone brass","serial_code":"SP0153","year":"2013"}'::jsonb, 'Brown', 'available', true, '2026-10-07T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000001', '/placeholders/bag-brown.svg', 'Louis Vuitton Speedy 30 in brown monogram', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000001' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000001', '/placeholders/bag-brown-angle.svg', 'Louis Vuitton Speedy 30 in brown monogram — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000001' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000001', '/placeholders/bag-brown-detail.svg', 'Louis Vuitton Speedy 30 in brown monogram — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000001' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000002', 'chanel-classic-flap-medium-black-caviar', (select id from public.brands where slug = 'chanel'), 'Classic Double Flap Medium', 'Chanel Classic Double Flap Medium Black Caviar GHW', 'bags', 'shoulder-bags', 465000, null, 'pristine', 'Corners perfect, holds shape. Hardware with very faint hairlines.', array['box', 'dust_bag', 'authenticity_card', 'receipt']::text[], 'Entrupy verified + in-house authentication', '{"measurements":"25.5 × 15.5 × 6.5 cm","material":"Caviar leather","color":"Black","hardware":"Gold-tone","serial_code":"Microchip","year":"2022"}'::jsonb, 'Black', 'available', true, '2026-10-06T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000002', '/placeholders/bag-black.svg', 'Chanel Classic Flap in black caviar', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000002' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000002', '/placeholders/bag-black-angle.svg', 'Chanel Classic Flap in black caviar — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000002' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000002', '/placeholders/bag-black-detail.svg', 'Chanel Classic Flap in black caviar — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000002' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000003', 'hermes-birkin-30-gold-togo', (select id from public.brands where slug = 'hermes'), 'Birkin 30', 'Hermès Birkin 30 Gold Togo GHW', 'bags', 'top-handle-bags', 1150000, null, 'brand_new', 'Unused, plastic on hardware.', array['box', 'dust_bag', 'receipt', 'lock_and_key', 'booklet']::text[], 'In-house authentication; store receipt included', '{"measurements":"30 × 22 × 16 cm","material":"Togo leather","color":"Gold (tan)","hardware":"Gold-plated","year":"2024 (Stamp B)"}'::jsonb, 'Tan', 'available', true, '2026-10-05T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000003', '/placeholders/bag-tan.svg', 'Hermès Birkin 30 in gold togo', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000003' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000003', '/placeholders/bag-tan-angle.svg', 'Hermès Birkin 30 in gold togo — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000003' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000003', '/placeholders/bag-tan-detail.svg', 'Hermès Birkin 30 in gold togo — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000003' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000004', 'dior-lady-dior-medium-red', (select id from public.brands where slug = 'dior'), 'Lady Dior Medium', 'Dior Lady Dior Medium Red Cannage Lambskin', 'bags', 'top-handle-bags', 215000, 240000, 'very_good', 'Slight corner wear and faint marks on back panel. Charms intact.', array['dust_bag', 'strap', 'authenticity_card']::text[], 'Entrupy verified', '{"measurements":"24 × 20 × 11 cm","material":"Lambskin","color":"Red","hardware":"Light gold-tone","year":"2019"}'::jsonb, 'Red', 'reserved', false, '2026-10-03T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000004', '/placeholders/bag-red.svg', 'Dior Lady Dior in red', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000004' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000004', '/placeholders/bag-red-angle.svg', 'Dior Lady Dior in red — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000004' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000004', '/placeholders/bag-red-detail.svg', 'Dior Lady Dior in red — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000004' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000005', 'gucci-ophidia-small-shoulder-bag', (select id from public.brands where slug = 'gucci'), 'Ophidia Small', 'Gucci Ophidia Small GG Supreme Shoulder Bag', 'bags', 'crossbody-bags', 62000, null, 'excellent', 'Very light wear on strap edges.', array['dust_bag', 'box']::text[], 'Entrupy verified', '{"measurements":"25 × 17 × 7 cm","material":"GG Supreme canvas & leather","color":"Beige / Ebony","hardware":"Antique gold-tone"}'::jsonb, 'Beige', 'available', false, '2026-10-02T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000005', '/placeholders/bag-cream.svg', 'Gucci Ophidia small shoulder bag', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000005' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000005', '/placeholders/bag-cream-angle.svg', 'Gucci Ophidia small shoulder bag — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000005' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000005', '/placeholders/bag-cream-detail.svg', 'Gucci Ophidia small shoulder bag — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000005' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000006', 'goyard-saint-louis-pm-green', (select id from public.brands where slug = 'goyard'), 'Saint Louis PM', 'Goyard Saint Louis PM Green', 'bags', 'tote-bags', 78000, null, 'good', 'Visible wear on corners and handle drops; canvas intact. Priced accordingly.', array['dust_bag']::text[], 'In-house authentication', '{"measurements":"34 × 27 × 14 cm","material":"Goyardine canvas","color":"Green"}'::jsonb, 'Green', 'sold', false, '2026-09-26T00:00:00.000Z', '2026-09-26T00:00:00.000Z')
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000006', '/placeholders/bag-green.svg', 'Goyard Saint Louis PM in green', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000006' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000006', '/placeholders/bag-green-angle.svg', 'Goyard Saint Louis PM in green — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000006' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000006', '/placeholders/bag-green-detail.svg', 'Goyard Saint Louis PM in green — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000006' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000007', 'rolex-submariner-date-126610ln', (select id from public.brands where slug = 'rolex'), 'Submariner Date', 'Rolex Submariner Date 126610LN', 'watches', 'sports-divers', 845000, null, 'pristine', 'Stickers removed, no visible scratches. Full links.', array['box', 'warranty_card', 'booklet', 'extra_links']::text[], 'Movement & serial verified by watchmaker', '{"reference_no":"126610LN","movement":"Automatic, Cal. 3235","case_size":"41 mm","material":"Oystersteel","color":"Black dial","year":"2023"}'::jsonb, 'Black', 'available', true, '2026-10-07T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000007', '/placeholders/watch-steel.svg', 'Rolex Submariner Date', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000007' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000007', '/placeholders/watch-steel-angle.svg', 'Rolex Submariner Date — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000007' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000007', '/placeholders/watch-steel-detail.svg', 'Rolex Submariner Date — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000007' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000008', 'audemars-piguet-royal-oak-15500st', (select id from public.brands where slug = 'audemars-piguet'), 'Royal Oak 41', 'Audemars Piguet Royal Oak 15500ST Black Dial', 'watches', 'mens-watches', 2350000, null, 'excellent', 'Light desk-diving marks on clasp. Polished lines crisp.', array['box', 'warranty_card', 'booklet']::text[], 'Movement & serial verified by watchmaker', '{"reference_no":"15500ST.OO.1220ST.03","movement":"Automatic, Cal. 4302","case_size":"41 mm","material":"Stainless steel","color":"Black dial","year":"2021"}'::jsonb, 'Black', 'available', true, '2026-10-04T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000008', '/placeholders/watch-black.svg', 'Audemars Piguet Royal Oak', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000008' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000008', '/placeholders/watch-black-angle.svg', 'Audemars Piguet Royal Oak — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000008' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000008', '/placeholders/watch-black-detail.svg', 'Audemars Piguet Royal Oak — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000008' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000009', 'cartier-panthere-de-cartier-small-yellow-gold', (select id from public.brands where slug = 'cartier'), 'Panthère de Cartier Small', 'Cartier Panthère de Cartier Small 18K Yellow Gold', 'watches', 'womens-watches', 1280000, 1350000, 'very_good', 'Fine scratches on bracelet consistent with use. Serviced 2025.', array['box', 'warranty_card']::text[], 'Verified by Cartier boutique service', '{"reference_no":"WGPN0008","movement":"Quartz","case_size":"22 × 30 mm","material":"18K yellow gold","color":"Silver dial"}'::jsonb, 'Gold', 'sold', false, '2026-09-23T00:00:00.000Z', '2026-09-23T00:00:00.000Z')
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000009', '/placeholders/watch-gold.svg', 'Cartier Panthère in yellow gold', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000009' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000009', '/placeholders/watch-gold-angle.svg', 'Cartier Panthère in yellow gold — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000009' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000009', '/placeholders/watch-gold-detail.svg', 'Cartier Panthère in yellow gold — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000009' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000010', 'tiffany-and-co-solitaire-ring-1-02ct', (select id from public.brands where slug = 'tiffany-and-co'), 'Tiffany Setting Solitaire', 'Tiffany & Co. Solitaire Diamond Ring 1.02ct', 'jewelry', 'diamonds', 685000, null, 'pristine', 'Freshly polished. Size 5.5, resizable.', array['box', 'certificate', 'receipt']::text[], 'GIA certificate + Tiffany diamond certificate', '{"material":"Platinum","color":"F","measurements":"1.02 ct round brilliant, VS1, Excellent cut","size":"5.5"}'::jsonb, 'Platinum', 'available', true, '2026-10-06T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000010', '/placeholders/ring-diamond.svg', 'Diamond solitaire ring', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000010' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000010', '/placeholders/ring-diamond-angle.svg', 'Diamond solitaire ring — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000010' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000010', '/placeholders/ring-diamond-detail.svg', 'Diamond solitaire ring — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000010' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000011', 'van-cleef-and-arpels-vintage-alhambra-pendant', (select id from public.brands where slug = 'van-cleef-and-arpels'), 'Vintage Alhambra Pendant', 'Van Cleef & Arpels Vintage Alhambra Pendant Mother-of-Pearl', 'jewelry', 'necklaces', 198000, null, 'excellent', 'Light surface scratches on gold, stone perfect.', array['box', 'certificate']::text[], 'In-house authentication; serial verified', '{"material":"18K yellow gold, mother-of-pearl","measurements":"Chain 42 cm"}'::jsonb, 'Gold', 'available', false, '2026-10-01T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000011', '/placeholders/necklace-gold.svg', 'Alhambra pendant necklace', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000011' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000011', '/placeholders/necklace-gold-angle.svg', 'Alhambra pendant necklace — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000011' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000011', '/placeholders/necklace-gold-detail.svg', 'Alhambra pendant necklace — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000011' and position = 2);
insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values ('00000000-0000-4000-8000-000000000012', 'louis-vuitton-zippy-wallet-monogram', (select id from public.brands where slug = 'louis-vuitton'), 'Zippy Wallet', 'Louis Vuitton Zippy Wallet Monogram', 'accessories', 'wallets', 28500, 32000, 'very_good', 'Light marks on interior card slots. Zipper smooth.', array['box', 'dust_bag']::text[], 'Entrupy verified', '{"measurements":"19.5 × 10.5 × 2.5 cm","material":"Monogram canvas","color":"Brown","hardware":"Gold-tone"}'::jsonb, 'Brown', 'available', false, '2026-10-05T00:00:00.000Z', null)
on conflict (slug) do nothing;
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000012', '/placeholders/wallet-brown.svg', 'Louis Vuitton Zippy Wallet', 0 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000012' and position = 0);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000012', '/placeholders/wallet-brown-angle.svg', 'Louis Vuitton Zippy Wallet — side view', 1 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000012' and position = 1);
insert into public.product_images (product_id, url, alt, position) select '00000000-0000-4000-8000-000000000012', '/placeholders/wallet-brown-detail.svg', 'Louis Vuitton Zippy Wallet — hardware detail', 2 where not exists (select 1 from public.product_images where product_id = '00000000-0000-4000-8000-000000000012' and position = 2);
insert into public.reviews (name, location, rating, body, item) select 'Patricia L.', 'Makati City', 5, 'Item was exactly as described — even better in person. Fast replies on Messenger and very careful packaging. Will definitely buy again!', 'Chanel Classic Flap' where not exists (select 1 from public.reviews where name = 'Patricia L.' and body = 'Item was exactly as described — even better in person. Fast replies on Messenger and very careful packaging. Will definitely buy again!');
insert into public.reviews (name, location, rating, body, item) select 'Miguel R.', 'Cebu City', 5, 'First time buying a pre-loved watch online and I was nervous, but they sent extra photos and a video of the movement. Arrived in Cebu in 2 days.', 'Rolex Datejust' where not exists (select 1 from public.reviews where name = 'Miguel R.' and body = 'First time buying a pre-loved watch online and I was nervous, but they sent extra photos and a video of the movement. Arrived in Cebu in 2 days.');
insert into public.reviews (name, location, rating, body, item) select 'Andrea S.', 'Quezon City', 5, 'Used their layaway and it was so easy to track my balance. Super legit and accommodating. Thank you HIGHLUX!', 'LV Neverfull MM' where not exists (select 1 from public.reviews where name = 'Andrea S.' and body = 'Used their layaway and it was so easy to track my balance. Super legit and accommodating. Thank you HIGHLUX!');
insert into public.reviews (name, location, rating, body, item) select 'Joanna T.', 'Davao City', 5, 'Authentic with complete inclusions. Paid via GCash, shipped the same day. Highly recommended seller.', 'Tiffany T Bracelet' where not exists (select 1 from public.reviews where name = 'Joanna T.' and body = 'Authentic with complete inclusions. Paid via GCash, shipped the same day. Highly recommended seller.');
insert into public.site_settings (key, value) values ('home', '{"heroImageUrl":"/placeholders/hero.svg","heroEyebrow":"Authentic Luxury, Timeless Investment.","heroHeadline":"Pre-Loved Luxury Bags","heroSubline":"Bags | Watches | Diamonds | Jewelry","heroScript":"Your Next Luxury Awaits.","heroCtaLabel":"Shop Now","heroCtaHref":"/shop"}'::jsonb) on conflict (key) do nothing;
commit;

-- Done. Next: sign up on the website, then make yourself admin:
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'YOUR-EMAIL');
