/**
 * Sample catalog used (a) when Supabase env vars are not set, so the site
 * renders out of the box, and (b) as the source for supabase/seed.sql.
 * Images are brand-free placeholders in /public/placeholders.
 */
import type { HomeContent, Product, Review } from "./types";

const img = (name: string, alt: string) => [
  { url: `/placeholders/${name}.svg`, alt },
  { url: `/placeholders/${name}-angle.svg`, alt: `${alt} — side view` },
  { url: `/placeholders/${name}-detail.svg`, alt: `${alt} — hardware detail` },
];

const daysAgo = (n: number) => new Date(Date.UTC(2026, 9, 8) - n * 86_400_000).toISOString();

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "louis-vuitton-speedy-30-monogram",
    brand: "Louis Vuitton", brandSlug: "louis-vuitton", model: "Speedy 30",
    title: "Louis Vuitton Speedy 30 Monogram",
    category: "bags", subCategory: "top-handle-bags",
    price: 48000, compareAtPrice: 55000,
    condition: "excellent", conditionNotes: "Light patina on vachetta handles. Clean interior. Minor scuffs on base corners.",
    inclusions: ["dust_bag", "lock_and_key"],
    authenticityMethod: "Entrupy verified", authenticityCertificateUrl: null,
    specs: { measurements: "30 × 21 × 17 cm", material: "Monogram coated canvas", color: "Brown", hardware: "Gold-tone brass", serial_code: "SP0153", year: "2013" },
    color: "Brown", images: img("bag-brown", "Louis Vuitton Speedy 30 in brown monogram"), status: "available", featured: true, createdAt: daysAgo(1),
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    slug: "chanel-classic-flap-medium-black-caviar",
    brand: "Chanel", brandSlug: "chanel", model: "Classic Double Flap Medium",
    title: "Chanel Classic Double Flap Medium Black Caviar GHW",
    category: "bags", subCategory: "shoulder-bags",
    price: 465000, compareAtPrice: null,
    condition: "pristine", conditionNotes: "Corners perfect, holds shape. Hardware with very faint hairlines.",
    inclusions: ["box", "dust_bag", "authenticity_card", "receipt"],
    authenticityMethod: "Entrupy verified + in-house authentication", authenticityCertificateUrl: null,
    specs: { measurements: "25.5 × 15.5 × 6.5 cm", material: "Caviar leather", color: "Black", hardware: "Gold-tone", serial_code: "Microchip", year: "2022" },
    color: "Black", images: img("bag-black", "Chanel Classic Flap in black caviar"), status: "available", featured: true, createdAt: daysAgo(2),
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    slug: "hermes-birkin-30-gold-togo",
    brand: "Hermès", brandSlug: "hermes", model: "Birkin 30",
    title: "Hermès Birkin 30 Gold Togo GHW",
    category: "bags", subCategory: "top-handle-bags",
    price: 1150000, compareAtPrice: null,
    condition: "brand_new", conditionNotes: "Unused, plastic on hardware.",
    inclusions: ["box", "dust_bag", "receipt", "lock_and_key", "booklet"],
    authenticityMethod: "In-house authentication; store receipt included", authenticityCertificateUrl: null,
    specs: { measurements: "30 × 22 × 16 cm", material: "Togo leather", color: "Gold (tan)", hardware: "Gold-plated", year: "2024 (Stamp B)" },
    color: "Tan", images: img("bag-tan", "Hermès Birkin 30 in gold togo"), status: "available", featured: true, createdAt: daysAgo(3),
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    slug: "dior-lady-dior-medium-red",
    brand: "Dior", brandSlug: "dior", model: "Lady Dior Medium",
    title: "Dior Lady Dior Medium Red Cannage Lambskin",
    category: "bags", subCategory: "top-handle-bags",
    price: 215000, compareAtPrice: 240000,
    condition: "very_good", conditionNotes: "Slight corner wear and faint marks on back panel. Charms intact.",
    inclusions: ["dust_bag", "strap", "authenticity_card"],
    authenticityMethod: "Entrupy verified", authenticityCertificateUrl: null,
    specs: { measurements: "24 × 20 × 11 cm", material: "Lambskin", color: "Red", hardware: "Light gold-tone" , year: "2019" },
    color: "Red", images: img("bag-red", "Dior Lady Dior in red"), status: "reserved", featured: false, createdAt: daysAgo(5),
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    slug: "gucci-ophidia-small-shoulder-bag",
    brand: "Gucci", brandSlug: "gucci", model: "Ophidia Small",
    title: "Gucci Ophidia Small GG Supreme Shoulder Bag",
    category: "bags", subCategory: "crossbody-bags",
    price: 62000, compareAtPrice: null,
    condition: "excellent", conditionNotes: "Very light wear on strap edges.",
    inclusions: ["dust_bag", "box"],
    authenticityMethod: "Entrupy verified", authenticityCertificateUrl: null,
    specs: { measurements: "25 × 17 × 7 cm", material: "GG Supreme canvas & leather", color: "Beige / Ebony", hardware: "Antique gold-tone" },
    color: "Beige", images: img("bag-cream", "Gucci Ophidia small shoulder bag"), status: "available", featured: false, createdAt: daysAgo(6),
  },
  {
    id: "00000000-0000-4000-8000-000000000006",
    slug: "goyard-saint-louis-pm-green",
    brand: "Goyard", brandSlug: "goyard", model: "Saint Louis PM",
    title: "Goyard Saint Louis PM Green",
    category: "bags", subCategory: "tote-bags",
    price: 78000, compareAtPrice: null,
    condition: "good", conditionNotes: "Visible wear on corners and handle drops; canvas intact. Priced accordingly.",
    inclusions: ["dust_bag"],
    authenticityMethod: "In-house authentication", authenticityCertificateUrl: null,
    specs: { measurements: "34 × 27 × 14 cm", material: "Goyardine canvas", color: "Green" },
    color: "Green", images: img("bag-green", "Goyard Saint Louis PM in green"), status: "sold", featured: false, createdAt: daysAgo(12),
  },
  {
    id: "00000000-0000-4000-8000-000000000007",
    slug: "rolex-submariner-date-126610ln",
    brand: "Rolex", brandSlug: "rolex", model: "Submariner Date",
    title: "Rolex Submariner Date 126610LN",
    category: "watches", subCategory: "sports-divers",
    price: 845000, compareAtPrice: null,
    condition: "pristine", conditionNotes: "Stickers removed, no visible scratches. Full links.",
    inclusions: ["box", "warranty_card", "booklet", "extra_links"],
    authenticityMethod: "Movement & serial verified by watchmaker", authenticityCertificateUrl: null,
    specs: { reference_no: "126610LN", movement: "Automatic, Cal. 3235", case_size: "41 mm", material: "Oystersteel", color: "Black dial", year: "2023" },
    color: "Black", images: img("watch-steel", "Rolex Submariner Date"), status: "available", featured: true, createdAt: daysAgo(1),
  },
  {
    id: "00000000-0000-4000-8000-000000000008",
    slug: "audemars-piguet-royal-oak-15500st",
    brand: "Audemars Piguet", brandSlug: "audemars-piguet", model: "Royal Oak 41",
    title: "Audemars Piguet Royal Oak 15500ST Black Dial",
    category: "watches", subCategory: "mens-watches",
    price: 2350000, compareAtPrice: null,
    condition: "excellent", conditionNotes: "Light desk-diving marks on clasp. Polished lines crisp.",
    inclusions: ["box", "warranty_card", "booklet"],
    authenticityMethod: "Movement & serial verified by watchmaker", authenticityCertificateUrl: null,
    specs: { reference_no: "15500ST.OO.1220ST.03", movement: "Automatic, Cal. 4302", case_size: "41 mm", material: "Stainless steel", color: "Black dial", year: "2021" },
    color: "Black", images: img("watch-black", "Audemars Piguet Royal Oak"), status: "available", featured: true, createdAt: daysAgo(4),
  },
  {
    id: "00000000-0000-4000-8000-000000000009",
    slug: "cartier-panthere-de-cartier-small-yellow-gold",
    brand: "Cartier", brandSlug: "cartier", model: "Panthère de Cartier Small",
    title: "Cartier Panthère de Cartier Small 18K Yellow Gold",
    category: "watches", subCategory: "womens-watches",
    price: 1280000, compareAtPrice: 1350000,
    condition: "very_good", conditionNotes: "Fine scratches on bracelet consistent with use. Serviced 2025.",
    inclusions: ["box", "warranty_card"],
    authenticityMethod: "Verified by Cartier boutique service", authenticityCertificateUrl: null,
    specs: { reference_no: "WGPN0008", movement: "Quartz", case_size: "22 × 30 mm", material: "18K yellow gold", color: "Silver dial" },
    color: "Gold", images: img("watch-gold", "Cartier Panthère in yellow gold"), status: "sold", featured: false, createdAt: daysAgo(15),
  },
  {
    id: "00000000-0000-4000-8000-000000000010",
    slug: "tiffany-and-co-solitaire-ring-1-02ct",
    brand: "Tiffany & Co.", brandSlug: "tiffany-and-co", model: "Tiffany Setting Solitaire",
    title: "Tiffany & Co. Solitaire Diamond Ring 1.02ct",
    category: "jewelry", subCategory: "diamonds",
    price: 685000, compareAtPrice: null,
    condition: "pristine", conditionNotes: "Freshly polished. Size 5.5, resizable.",
    inclusions: ["box", "certificate", "receipt"],
    authenticityMethod: "GIA certificate + Tiffany diamond certificate", authenticityCertificateUrl: null,
    specs: { material: "Platinum", color: "F", measurements: "1.02 ct round brilliant, VS1, Excellent cut", size: "5.5" },
    color: "Platinum", images: img("ring-diamond", "Diamond solitaire ring"), status: "available", featured: true, createdAt: daysAgo(2),
  },
  {
    id: "00000000-0000-4000-8000-000000000011",
    slug: "van-cleef-and-arpels-vintage-alhambra-pendant",
    brand: "Van Cleef & Arpels", brandSlug: "van-cleef-and-arpels", model: "Vintage Alhambra Pendant",
    title: "Van Cleef & Arpels Vintage Alhambra Pendant Mother-of-Pearl",
    category: "jewelry", subCategory: "necklaces",
    price: 198000, compareAtPrice: null,
    condition: "excellent", conditionNotes: "Light surface scratches on gold, stone perfect.",
    inclusions: ["box", "certificate"],
    authenticityMethod: "In-house authentication; serial verified", authenticityCertificateUrl: null,
    specs: { material: "18K yellow gold, mother-of-pearl", measurements: "Chain 42 cm" },
    color: "Gold", images: img("necklace-gold", "Alhambra pendant necklace"), status: "available", featured: false, createdAt: daysAgo(7),
  },
  {
    id: "00000000-0000-4000-8000-000000000012",
    slug: "louis-vuitton-zippy-wallet-monogram",
    brand: "Louis Vuitton", brandSlug: "louis-vuitton", model: "Zippy Wallet",
    title: "Louis Vuitton Zippy Wallet Monogram",
    category: "accessories", subCategory: "wallets",
    price: 28500, compareAtPrice: 32000,
    condition: "very_good", conditionNotes: "Light marks on interior card slots. Zipper smooth.",
    inclusions: ["box", "dust_bag"],
    authenticityMethod: "Entrupy verified", authenticityCertificateUrl: null,
    specs: { measurements: "19.5 × 10.5 × 2.5 cm", material: "Monogram canvas", color: "Brown", hardware: "Gold-tone" },
    color: "Brown", images: img("wallet-brown", "Louis Vuitton Zippy Wallet"), status: "available", featured: false, createdAt: daysAgo(3),
  },
];

export const SAMPLE_REVIEWS: Review[] = [
  { id: "r1", name: "Patricia L.", location: "Makati City", rating: 5, item: "Chanel Classic Flap", body: "Item was exactly as described — even better in person. Fast replies on Messenger and very careful packaging. Will definitely buy again!" },
  { id: "r2", name: "Miguel R.", location: "Cebu City", rating: 5, item: "Rolex Datejust", body: "First time buying a pre-loved watch online and I was nervous, but they sent extra photos and a video of the movement. Arrived in Cebu in 2 days." },
  { id: "r3", name: "Andrea S.", location: "Quezon City", rating: 5, item: "LV Neverfull MM", body: "Used their layaway and it was so easy to track my balance. Super legit and accommodating. Thank you HIGHLUX!" },
  { id: "r4", name: "Joanna T.", location: "Davao City", rating: 5, item: "Tiffany T Bracelet", body: "Authentic with complete inclusions. Paid via GCash, shipped the same day. Highly recommended seller." },
];

export const DEFAULT_HOME_CONTENT: HomeContent = {
  heroImageUrl: "/placeholders/hero.svg",
  heroEyebrow: "Authentic Luxury, Timeless Investment.",
  heroHeadline: "Pre-Loved Luxury Bags",
  heroSubline: "Bags | Watches | Diamonds | Jewelry",
  heroScript: "Your Next Luxury Awaits.",
  heroCtaLabel: "Shop Now",
  heroCtaHref: "/shop",
};
