// Builds supabase/seed.sql from lib/sample-data.ts + lib/catalog.ts.
// Run: npx tsx scripts/generate-seed.ts
import { writeFileSync } from "node:fs";
import { BRANDS } from "../lib/catalog";
import { DEFAULT_HOME_CONTENT, SAMPLE_PRODUCTS, SAMPLE_REVIEWS } from "../lib/sample-data";

const q = (v: unknown) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (xs: string[], type: string) => `array[${xs.map(q).join(", ")}]::${type}[]`;

const out: string[] = ["-- Generated by scripts/generate-seed.ts — do not edit by hand.", "begin;"];

BRANDS.forEach((b, i) =>
  out.push(
    `insert into public.brands (name, slug, categories, sort_order) values (${q(b.name)}, ${q(b.slug)}, ${arr(b.categories, "public.product_category")}, ${i}) on conflict (slug) do nothing;`,
  ),
);

for (const p of SAMPLE_PRODUCTS) {
  out.push(`insert into public.products (id, slug, brand_id, model, title, category, sub_category, price, compare_at_price, condition, condition_notes, inclusions, authenticity_method, specs, color, status, featured, created_at, sold_at)
values (${q(p.id)}, ${q(p.slug)}, (select id from public.brands where slug = ${q(p.brandSlug)}), ${q(p.model)}, ${q(p.title)}, ${q(p.category)}, ${q(p.subCategory)}, ${p.price}, ${p.compareAtPrice ?? "null"}, ${q(p.condition)}, ${q(p.conditionNotes)}, ${arr(p.inclusions, "text")}, ${q(p.authenticityMethod)}, ${q(JSON.stringify(p.specs))}::jsonb, ${q(p.color)}, ${q(p.status)}, ${p.featured}, ${q(p.createdAt)}, ${p.status === "sold" ? q(p.createdAt) : "null"})
on conflict (slug) do nothing;`);
  p.images.forEach((im, i) =>
    out.push(`insert into public.product_images (product_id, url, alt, position) select ${q(p.id)}, ${q(im.url)}, ${q(im.alt)}, ${i} where not exists (select 1 from public.product_images where product_id = ${q(p.id)} and position = ${i});`),
  );
}

for (const r of SAMPLE_REVIEWS)
  out.push(`insert into public.reviews (name, location, rating, body, item) select ${q(r.name)}, ${q(r.location)}, ${r.rating}, ${q(r.body)}, ${q(r.item)} where not exists (select 1 from public.reviews where name = ${q(r.name)} and body = ${q(r.body)});`);

out.push(`insert into public.site_settings (key, value) values ('home', ${q(JSON.stringify(DEFAULT_HOME_CONTENT))}::jsonb) on conflict (key) do nothing;`);
out.push("commit;", "");

writeFileSync("supabase/seed.sql", out.join("\n"));
console.log(`Wrote supabase/seed.sql (${SAMPLE_PRODUCTS.length} products)`);
